kind: "AppStack"
apiVersion: "v1"
runConfig:
  concurrency: 80
  cpu: 1
  memoryMiB: 512
env:
  - variable: NEXT_PUBLIC_FIREBASE_API_KEY
    availability: ["BUILD", "RUNTIME"]
  - variable: NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
    availability: ["BUILD", "RUNTIME"]
  - variable: NEXT_PUBLIC_FIREBASE_PROJECT_ID
    availability: ["BUILD", "RUNTIME"]
  - variable: NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
    availability: ["BUILD", "RUNTIME"]
  - variable: NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
    availability: ["BUILD", "RUNTIME"]
  - variable: NEXT_PUBLIC_FIREBASE_APP_ID
    availability: ["BUILD", "RUNTIME"]
