type UserV2 @table(key: "id") {
  id: String!
  googleId: String!
  createdAt: Timestamp!
  displayName: String
  email: String
  photoUrl: String
  refreshToken: String
}

type AgentV2 @table(key: "id") {
  id: String!
  user: UserV2!
  name: String!
  type: String!
  status: String!
  createdAt: Timestamp!
  schedule: String
  lastRun: Timestamp
  settings: String
}

type RunV2 @table {
  agent: AgentV2!
  timestamp: Timestamp!
  status: String!
  details: String!
  logs: [String]
}